### ISSUE TITLE
Deprecation warning due to "import"

### ISSUE THREAD

**Issue by rusitschka** [scheleaap/ansible-role-snapcast#2]
Thanks for your ansible role. I've been using it since years. :-)

Currently I'm getting 
```
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in version 2.16.
```
Are you aware of this?

**Comment by rusitschka** [comment]
PR works for me: https://github.com/scheleaap/ansible-role-snapcast/pull/3

**Comment by scheleaap** [comment]
Thanks for the warning and the fix! I wasn't aware of that yet, probably because I didn't upgrade my Ansible in a while.

I'm glad to hear the role is useful for others, too :-).
